name: lost_found_app
description: Campus Lost & Found Flutter App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  lottie: ^3.1.2
  image_picker: ^1.2.1        # For camera and gallery access
  geolocator: ^10.1.0        # To get current GPS coordinates
  maps_toolkit: ^2.0.1       # To check if a point is inside a polygon
  supabase_flutter: ^2.12.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/campus.jpg
    - assets/images/unifound_logo.png